require("plugins.markdown.mdeval")
require("plugins.markdown.image")
require("plugins.markdown.vimwiki")
require("plugins.markdown.taskopen")
require("plugins.markdown.taskwiki")
require("plugins.markdown.venn")
require("plugins.markdown.calendar")
