#!/bin/bash

projectname=$1

if [ -z $1 ] then
  echo "Usage: $0 <[path/]projectname>"
fi

mkdir $projectname
mkdir $projectname/src
mkdir $projectname/build

touch $projectname/src/main.c

echo "#!/bin/bash\ngcc ./src/main.c -o ./build/main" > $projectname/build.sh
chmod u+x $projectname/build/build.sh

echo "#!/bin/bash\n./build/main" > $projectname/run.sh
chmod u+x $projectname/run.sh
