#!/bin/bash

projectname=$1

if [ -z "$1" ]; then
  echo "Usage: $0 <[path/]projectname>"
fi

mkdir $projectname
mkdir $projectname/src
mkdir $projectname/build

touch $projectname/src/main.c

echo -e "#!/bin/bash\n\ngcc ./src/main.c -o ./build/main" > "$projectname/build.sh"
chmod u+x "$projectname/build.sh"

echo -e "#!/bin/bash\n\n./build/main" > "$projectname/run.sh"
chmod u+x "$projectname/run.sh"

cd "$projectname"
nvim
