#!/usr/bin/env bash

date="No Date"
subject="No Subject"
to="No Recipient"
from="No Sender"
message_id=""

echo "" > /home/rolf/foo/debug

while read line
do
  # echo "${line}" > /home/rolf/foo/debug
  
  if [[ -z "${line}" ]]; then
    continue
  fi
  
  if [[ "${line}" =~ ^Subject:\ (.*)$  ]]; then
    subject="${BASH_REMATCH[1]}"
  fi
  
  if [[ "${line}" =~ ^Date:\ (.*)$  ]]; then
    date="${BASH_REMATCH[1]}"
  fi
  
  if [[ "${line}" =~ ^To:\ (.*)$  ]]; then
    to="${BASH_REMATCH[1]}"
  fi
  
  if [[ "${line}" =~ ^From:\ (.*)$  ]]; then
    from="${BASH_REMATCH[1]}"
  fi
  
  if [[ "${line}" =~ ^Message-Id:\ (\<.*\>)$ ]]; then
    message_id="${BASH_REMATCH[1]}"
  fi
done

echo "${date}" >> /home/rolf/foo/debug
echo "${to}" >> /home/rolf/foo/debug
echo "${from}" >> /home/rolf/foo/debug
echo "${subject}" >> /home/rolf/foo/debug
echo "${message_id}" >> /home/rolf/foo/debug


task add "Message-ID: ${message_id}" +email +neomutt
id=$(task +LATEST _uuid)

task "${id}" annotate "Date: ${date}"
task "${id}" annotate "From: ${from}"
task "${id}" annotate "To: ${to}"
task "${id}" annotate "Subject: ${subject}"
task "${id}" annotate "----------------------"
task "${id}" annotate "Message-ID: ${message_id}"

