#!/bin/bash

if [ -z "$1" ]
then echo "Name required"
else 
  cp "$HOME/learning/r/quick/plot.R" "$HOME/learning/r/quick/plot.R.bak" && 
  cp "$HOME/learning/r/quick/saved/$1.R" "$HOME/learning/r/quick/plot.R" &&

  cp "$HOME/learning/r/quick/data.csv" "$HOME/learning/r/quick/data.csv.bak" && 
  cp "$HOME/learning/r/quick/saved/$1.csv" "$HOME/learning/r/quick/data.csv" && 
  set -i "s/$1.csv/data.csv/g" "$HOME/learning/r/quick/plot.R"

  cp "$HOME/learning/r/quick/plot.png" "$HOME/learning/r/quick/plot.png.bak" && 
  cp "$HOME/learning/r/quick/saved/$1.png" "$HOME/learning/r/quick/plot.png" && 
  set -i "s/$1.png/plot.png/g" "$HOME/learning/r/quick/plot.R"
fi
