#!/bin/bash

if [ -z "$1" ]; then
 echo "Usage: $0 <min>"
 exit 1
fi

let arg1=$1

let num=$((arg1 * 60 / 15))

> /home/rolf/scripts/bar.txt
for((i = 0; i < $((num)); i++)); do
 echo -n ":" >> /home/rolf/scripts/bar.txt
done
echo 0 > /home/rolf/scripts/pause.txt
