#!/bin/bash

date=$(date +%Y_%m_%d-%H:%M)
uuid=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1)

if [ -n "$1" ]; then
  title="${1}_${uuid}"
else
  title="${uuid}"
fi

if [ -n "$2" ]; then
  spath="${2%/}"
else
  spath="$HOME/shell_logs"
  mkdir -p $spath
fi

filename="${date}_${title}"

mkdir -p "${HOME}/tmp"

script -q --timing="${HOME}/tmp/${filename}.timing" -c "${SHELL}" "${HOME}/tmp/${filename}" &&
  
ansi2txt "${HOME}/tmp/${filename}" | sed 's/^.*echo ##\(.*\)$/################################################################################\n#### \1\n################################################################################/'| tr -d "\r" |  sed 's/^.*\x08/$ /' | sed 's/^% *\[rolf/[rolf/'  > "${spath}/${filename}" &&

echo "${spath}/${filename}"

